spring.application.name=IT342-Catamco-Lab2

spring.datasource.url=jdbc:mysql://localhost:3306/auth_system
spring.datasource.username=root
spring.datasource.password=Danise.123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8080

jwt.secret=it342_secret
jwt.expiration=86400000